import Sargis from '@/assets/images/icons/team/photo1.jpg';
import Bagrat from '@/assets/images/icons/team/photo2.jpg';
import Gor from '@/assets/images/icons/team/photo3.jpg';
import Maral from '@/assets/images/icons/team/photo4.jpg';
import Hakob from '@/assets/images/icons/team/photo5.jpg';
import Eva from '@/assets/images/icons/team/photo6.jpg';
import Kohar from '@/assets/images/icons/team/photo7.jpg';
import Ararat from '@/assets/images/icons/team/photo8.jpg';
import Eduard from '@/assets/images/icons/team/photo9.jpg';

const socials = {
  sargis: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
    'https://www.youtube.com/1',
    'https://dribbble.com/shots/20466236-Apres-Use-Cases-pages',
    'https://www.behance.net/gallery/161415897/illustration-Portraits-II?tracking_source=search_projects',
  ],
  bagrat: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
    'https://www.youtube.com/2',
    'https://dribbble.com/shots/20466238-3d-city',
    'https://www.behance.net/gallery/159042995/Moomin-For-Willow-%28Music-Video%29?tracking_source=search_projects',
  ],
  gor: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/viktoriya-afitova/',
    'https://www.youtube.com/3',
    'https://dribbble.com/shots/20467517-Illustration',
    'https://www.behance.net/gallery/136562459/SWAG-Brand-Film?tracking_source=search_projects',
  ],
  maral: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/viktoriya-afitova/',
    'https://www.youtube.com/4',
    'https://dribbble.com/shots/20464065-Radial-Chart',
    'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
  ],
  hakob: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/klik/',
    'https://www.youtube.com/5',
    'https://dribbble.com/shots/20466942-Blue-Mountain-Bakery-Logo-Design',
    'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
  ],
  vosgi: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/diana-balaban-b8133a229',
    'https://www.youtube.com/6',
    'https://dribbble.com/shots/20462203-Fruit-Sticker-Pt-IX',
    'https://www.behance.net/gallery/117807877/Pasta-Casalinga-Seattle-Website-Illustrations?tracking_source=search_projects',
  ],
  kohar: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/maryia-kashkan-466654249/',
    'https://www.youtube.com/7',
    'https://dribbble.com/shots/20458358-Soundsystem',
    'https://www.behance.net/gallery/161974161/From-the-streets-of-Old-Quarter-of-Dubai?tracking_source=search_projects',
  ],
  ararat: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/игорь-корж-0a673a21b/',
    'https://www.youtube.com/8',
    'https://dribbble.com/shots/20460923-Mini-Mtn',
    'https://www.behance.net/gallery/159157823/MOSTRO?tracking_source=search_projects',
  ],
  eduard: [
    'https://www.facebook.com',
    'https://twitter.com',
    'https://www.linkedin.com/in/alexandra-bone-78a3b8b3/',
    'https://www.youtube.com/9',
    'https://dribbble.com/shots/20460477-Do-Not-Disturb-Reminder',
    'https://www.behance.net/gallery/132606491/PLANT-BIRDS?tracking_source=search_projects',
  ],
};

const teamCardsEN = [
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: Eduard,
    social: socials.eduard,
  },
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: Eduard,
    social: socials.eduard,
  },
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: Eduard,
    social: socials.eduard,
  },
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: Eduard,
    social: socials.eduard,
  },
];

const teamCardsRU = [
  {
    name: 'Сарджис Григор',
    profession: 'Аналитик данных',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Баграт Лео',
    profession: 'Инженер данных',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Гор Саргис',
    profession: 'Аналитик данных',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Марал Мари',
    profession: 'Аналитик данных',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Якоб Жираир',
    profession: 'Инженер данных',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Ева Возги',
    profession: 'Исследователь данных',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Коар Марина',
    profession: 'Исследователь данных',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Арарат Оанесс',
    profession: 'Аналитик данных',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Эдуар Возги',
    profession: 'Исследователь данных',
    photo: Eduard,
    social: socials.eduard,
  },
  {
    name: 'Сарджис Григор',
    profession: 'Аналитик данных',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Баграт Лео',
    profession: 'Инженер данных',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Гор Саргис',
    profession: 'Аналитик данных',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Марал Мари',
    profession: 'Аналитик данных',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Якоб Жираир',
    profession: 'Инженер данных',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Ева Возги',
    profession: 'Исследователь данных',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Коар Марина',
    profession: 'Исследователь данных',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Арарат Оанесс',
    profession: 'Аналитик данных',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Эдуар Возги',
    profession: 'Исследователь данных',
    photo: Eduard,
    social: socials.eduard,
  },
  {
    name: 'Сарджис Григор',
    profession: 'Аналитик данных',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Баграт Лео',
    profession: 'Инженер данных',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Гор Саргис',
    profession: 'Аналитик данных',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Марал Мари',
    profession: 'Аналитик данных',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Якоб Жираир',
    profession: 'Инженер данных',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Ева Возги',
    profession: 'Исследователь данных',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Коар Марина',
    profession: 'Исследователь данных',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Арарат Оанесс',
    profession: 'Аналитик данных',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Эдуар Возги',
    profession: 'Исследователь данных',
    photo: Eduard,
    social: socials.eduard,
  },
  {
    name: 'Сарджис Григор',
    profession: 'Аналитик данных',
    photo: Sargis,
    social: socials.sargis,
  },
  {
    name: 'Баграт Лео',
    profession: 'Инженер данных',
    photo: Bagrat,
    social: socials.bagrat,
  },
  {
    name: 'Гор Саргис',
    profession: 'Аналитик данных',
    photo: Gor,
    social: socials.gor,
  },
  {
    name: 'Марал Мари',
    profession: 'Аналитик данных',
    photo: Maral,
    social: socials.maral,
  },
  {
    name: 'Якоб Жираир',
    profession: 'Инженер данных',
    photo: Hakob,
    social: socials.hakob,
  },
  {
    name: 'Ева Возги',
    profession: 'Исследователь данных',
    photo: Eva,
    social: socials.vosgi,
  },
  {
    name: 'Коар Марина',
    profession: 'Исследователь данных',
    photo: Kohar,
    social: socials.kohar,
  },
  {
    name: 'Арарат Оанесс',
    profession: 'Аналитик данных',
    photo: Ararat,
    social: socials.ararat,
  },
  {
    name: 'Эдуар Возги',
    profession: 'Исследователь данных',
    photo: Eduard,
    social: socials.eduard,
  },
];

export const teamCards = { en: teamCardsEN, ru: teamCardsRU };
