import photo1 from '@/assets/images/icons/team/photo1.jpg';
import photo2 from '@/assets/images/icons/team/photo2.jpg';
import photo3 from '@/assets/images/icons/team/photo3.jpg';
import photo4 from '@/assets/images/icons/team/photo4.jpg';
import photo5 from '@/assets/images/icons/team/photo5.jpg';
import photo6 from '@/assets/images/icons/team/photo6.jpg';
import photo7 from '@/assets/images/icons/team/photo7.jpg';
import photo8 from '@/assets/images/icons/team/photo8.jpg';
import photo9 from '@/assets/images/icons/team/photo9.jpg';

export const teamCards = [
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: photo1,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/1',
      'https://dribbble.com/shots/20466236-Apres-Use-Cases-pages',
      'https://www.behance.net/gallery/161415897/illustration-Portraits-II?tracking_source=search_projects',
    ],
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: photo2,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/2',
      'https://dribbble.com/shots/20466238-3d-city',
      'https://www.behance.net/gallery/159042995/Moomin-For-Willow-%28Music-Video%29?tracking_source=search_projects',
    ],
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: photo3,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/3',
      'https://dribbble.com/shots/20467517-Illustration',
      'https://www.behance.net/gallery/136562459/SWAG-Brand-Film?tracking_source=search_projects',
    ],
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: photo4,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/4',
      'https://dribbble.com/shots/20464065-Radial-Chart',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: photo5,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/klik/',
      'https://www.youtube.com/5',
      'https://dribbble.com/shots/20466942-Blue-Mountain-Bakery-Logo-Design',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: photo6,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/diana-balaban-b8133a229',
      'https://www.youtube.com/6',
      'https://dribbble.com/shots/20462203-Fruit-Sticker-Pt-IX',
      'https://www.behance.net/gallery/117807877/Pasta-Casalinga-Seattle-Website-Illustrations?tracking_source=search_projects',
    ],
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: photo7,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/maryia-kashkan-466654249/',
      'https://www.youtube.com/7',
      'https://dribbble.com/shots/20458358-Soundsystem',
      'https://www.behance.net/gallery/161974161/From-the-streets-of-Old-Quarter-of-Dubai?tracking_source=search_projects',
    ],
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: photo8,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/игорь-корж-0a673a21b/',
      'https://www.youtube.com/8',
      'https://dribbble.com/shots/20460923-Mini-Mtn',
      'https://www.behance.net/gallery/159157823/MOSTRO?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: photo9,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/alexandra-bone-78a3b8b3/',
      'https://www.youtube.com/9',
      'https://dribbble.com/shots/20460477-Do-Not-Disturb-Reminder',
      'https://www.behance.net/gallery/132606491/PLANT-BIRDS?tracking_source=search_projects',
    ],
  },
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: photo1,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/1',
      'https://dribbble.com/shots/20466236-Apres-Use-Cases-pages',
      'https://www.behance.net/gallery/161415897/illustration-Portraits-II?tracking_source=search_projects',
    ],
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: photo2,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/2',
      'https://dribbble.com/shots/20466238-3d-city',
      'https://www.behance.net/gallery/159042995/Moomin-For-Willow-%28Music-Video%29?tracking_source=search_projects',
    ],
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: photo3,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/3',
      'https://dribbble.com/shots/20467517-Illustration',
      'https://www.behance.net/gallery/136562459/SWAG-Brand-Film?tracking_source=search_projects',
    ],
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: photo4,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/4',
      'https://dribbble.com/shots/20464065-Radial-Chart',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: photo5,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/klik/',
      'https://www.youtube.com/5',
      'https://dribbble.com/shots/20466942-Blue-Mountain-Bakery-Logo-Design',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: photo6,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/diana-balaban-b8133a229',
      'https://www.youtube.com/6',
      'https://dribbble.com/shots/20462203-Fruit-Sticker-Pt-IX',
      'https://www.behance.net/gallery/117807877/Pasta-Casalinga-Seattle-Website-Illustrations?tracking_source=search_projects',
    ],
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: photo7,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/maryia-kashkan-466654249/',
      'https://www.youtube.com/7',
      'https://dribbble.com/shots/20458358-Soundsystem',
      'https://www.behance.net/gallery/161974161/From-the-streets-of-Old-Quarter-of-Dubai?tracking_source=search_projects',
    ],
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: photo8,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/игорь-корж-0a673a21b/',
      'https://www.youtube.com/8',
      'https://dribbble.com/shots/20460923-Mini-Mtn',
      'https://www.behance.net/gallery/159157823/MOSTRO?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: photo9,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/alexandra-bone-78a3b8b3/',
      'https://www.youtube.com/9',
      'https://dribbble.com/shots/20460477-Do-Not-Disturb-Reminder',
      'https://www.behance.net/gallery/132606491/PLANT-BIRDS?tracking_source=search_projects',
    ],
  },
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: photo1,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/1',
      'https://dribbble.com/shots/20466236-Apres-Use-Cases-pages',
      'https://www.behance.net/gallery/161415897/illustration-Portraits-II?tracking_source=search_projects',
    ],
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: photo2,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/2',
      'https://dribbble.com/shots/20466238-3d-city',
      'https://www.behance.net/gallery/159042995/Moomin-For-Willow-%28Music-Video%29?tracking_source=search_projects',
    ],
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: photo3,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/3',
      'https://dribbble.com/shots/20467517-Illustration',
      'https://www.behance.net/gallery/136562459/SWAG-Brand-Film?tracking_source=search_projects',
    ],
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: photo4,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/4',
      'https://dribbble.com/shots/20464065-Radial-Chart',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: photo5,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/klik/',
      'https://www.youtube.com/5',
      'https://dribbble.com/shots/20466942-Blue-Mountain-Bakery-Logo-Design',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: photo6,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/diana-balaban-b8133a229',
      'https://www.youtube.com/6',
      'https://dribbble.com/shots/20462203-Fruit-Sticker-Pt-IX',
      'https://www.behance.net/gallery/117807877/Pasta-Casalinga-Seattle-Website-Illustrations?tracking_source=search_projects',
    ],
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: photo7,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/maryia-kashkan-466654249/',
      'https://www.youtube.com/7',
      'https://dribbble.com/shots/20458358-Soundsystem',
      'https://www.behance.net/gallery/161974161/From-the-streets-of-Old-Quarter-of-Dubai?tracking_source=search_projects',
    ],
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: photo8,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/игорь-корж-0a673a21b/',
      'https://www.youtube.com/8',
      'https://dribbble.com/shots/20460923-Mini-Mtn',
      'https://www.behance.net/gallery/159157823/MOSTRO?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: photo9,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/alexandra-bone-78a3b8b3/',
      'https://www.youtube.com/9',
      'https://dribbble.com/shots/20460477-Do-Not-Disturb-Reminder',
      'https://www.behance.net/gallery/132606491/PLANT-BIRDS?tracking_source=search_projects',
    ],
  },
  {
    name: 'Sargis Grigor',
    profession: 'Data analyst',
    photo: photo1,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/1',
      'https://dribbble.com/shots/20466236-Apres-Use-Cases-pages',
      'https://www.behance.net/gallery/161415897/illustration-Portraits-II?tracking_source=search_projects',
    ],
  },
  {
    name: 'Bagrat Leo',
    profession: 'Data engineer',
    photo: photo2,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/артём-ильинчик-9b5584221/',
      'https://www.youtube.com/2',
      'https://dribbble.com/shots/20466238-3d-city',
      'https://www.behance.net/gallery/159042995/Moomin-For-Willow-%28Music-Video%29?tracking_source=search_projects',
    ],
  },
  {
    name: 'Gor Sargis',
    profession: 'Data analyst',
    photo: photo3,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/3',
      'https://dribbble.com/shots/20467517-Illustration',
      'https://www.behance.net/gallery/136562459/SWAG-Brand-Film?tracking_source=search_projects',
    ],
  },
  {
    name: 'Maral Mari',
    profession: 'Data analyst',
    photo: photo4,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/viktoriya-afitova/',
      'https://www.youtube.com/4',
      'https://dribbble.com/shots/20464065-Radial-Chart',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Hakob Jirair',
    profession: 'Data engineer',
    photo: photo5,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/klik/',
      'https://www.youtube.com/5',
      'https://dribbble.com/shots/20466942-Blue-Mountain-Bakery-Logo-Design',
      'https://www.behance.net/gallery/155755403/CultureCo-Identity-system?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eva Vosgi',
    profession: 'Data scientist',
    photo: photo6,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/diana-balaban-b8133a229',
      'https://www.youtube.com/6',
      'https://dribbble.com/shots/20462203-Fruit-Sticker-Pt-IX',
      'https://www.behance.net/gallery/117807877/Pasta-Casalinga-Seattle-Website-Illustrations?tracking_source=search_projects',
    ],
  },
  {
    name: 'Kohar Marine',
    profession: 'Data scientist',
    photo: photo7,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/maryia-kashkan-466654249/',
      'https://www.youtube.com/7',
      'https://dribbble.com/shots/20458358-Soundsystem',
      'https://www.behance.net/gallery/161974161/From-the-streets-of-Old-Quarter-of-Dubai?tracking_source=search_projects',
    ],
  },
  {
    name: 'Ararat Ohannes',
    profession: 'Data analyst',
    photo: photo8,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/игорь-корж-0a673a21b/',
      'https://www.youtube.com/8',
      'https://dribbble.com/shots/20460923-Mini-Mtn',
      'https://www.behance.net/gallery/159157823/MOSTRO?tracking_source=search_projects',
    ],
  },
  {
    name: 'Eduard Vosgi',
    profession: 'Data scientist',
    photo: photo9,
    social: [
      'https://www.facebook.com',
      'https://twitter.com',
      'https://www.linkedin.com/in/alexandra-bone-78a3b8b3/',
      'https://www.youtube.com/9',
      'https://dribbble.com/shots/20460477-Do-Not-Disturb-Reminder',
      'https://www.behance.net/gallery/132606491/PLANT-BIRDS?tracking_source=search_projects',
    ],
  },
];
