name: 'Lint checker, deploy'

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn lint
