name: 'Lint checker, deploy'

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn lint
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn deploy
