name: 'Lint checker, deploy'

on: [push]

jobs:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./modsen-themeforest-ensome-hollow
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn lint
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn deploy
